INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Charlotte','Foenkinos, David','Editions Gallimard',72);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Le Royaume','Carrére, Emmanuel','POL Editeur',60);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Chanson douce','Slimani, Leéla','Editions Gallimard',50);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('L''amie prodigieuse (Tome 2) - Le nouveau nom','Ferrante, Elena','Editions Gallimard',50);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Article 353 du code pénal','Viel, Tanguy','Minuit',43);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Les jours de ton absence','Walsh, Rosie','Les escales éditions',41);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Les Bourgeois','Ferney, Alice','éEditions Actes Sud',41);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Temps glaciaires','Vargas, Fred','Flammarion',39);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Réparer les vivants','Kerangal, Maylis de','Editions Gallimard',38);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Ce qui reste de nos vies','Shalev, Zeruya','Editions Gallimard',36);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('La Veille de presque tout','Del Arbol, Victor','éEditions Actes Sud',30);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('L''ordre du jour','Vuillard, Eric','éEditions Actes Sud',30);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('La sorciére','Léckberg Camilla','éEditions Actes Sud',30);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Les mille et une gaffes de l''ange gardien Ariel Auvinen','Paasilinna, Arto','Editions Denoél',29);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Pour que tu ne te perdes pas dans le quartier','Modiano, Patrick','Editions Gallimard',29);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Culottées. Des femmes qui ne font que ce qu''elles veulent (Tome 2)','Bagieu, Pénélope','Gallimard BD',29);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Millénium 4 - Ce qui ne me tue pas','Lagercrantz, David','éEditions Actes Sud',28);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Le collier rouge','Rufin, Jean-Christophe','Editions Gallimard',28);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Barbarie 2.0','Japp, Andrea H.','Flammarion',27);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Du sang sur la glace','Nesbo, Jo','Editions Gallimard',26);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Dans la forét','Hegland, Jean','éEditions Gallmeister',25);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('L''Art de perdre','Zeniter, Alice','Flammarion',25);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Le beau mystére','Penny, Louise','éEditions Actes Sud',25);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Désorientale','Négar Djavadi','Liana Levi',24);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Une famille délicieuse','Marsh, Willa','Autrement',24);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Ils vont tuer Robert Kennedy','Dugain, Marc','Editions Gallimard',23);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Le Garéon qui ne pleurait plus','Schulman, Ninni','Seuil',22);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Attends-moi au ciel','Salem, Carlos','Eéditions Actes Sud',22);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('La Beauté des jours','Gallay, Claudie','Eéditions Actes Sud',22);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Les disparus du phare','May, Peter','éEditions du Rouergue',21);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Ne pars pas avant moi','Rouart, Jean-Marie','Editions Gallimard',21);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('L''Heure indigo','Harmel, Kristin','Editions Denoél',21);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Les soeurs ennemies','Kellerman, Jonathan','Le Seuil',21);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Fermé pour l''hiver','Horst, Jorn Lier','Editions Gallimard',21);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('La terre qui les sépare','Matar, Hisham','Editions Gallimard',20);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Dieu, Allah, moi et les autres','Bachi, Salim','Editions Gallimard',20);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Ma mére, cette inconnue','Labro, Philippe','Editions Gallimard',20);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Incident voyageurs','Frioux, Dalibor','Seuil',19);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Hérétiques','Padura Fuentes, Leonardo','Anne-Marie Métailié',19);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Karpathia','Menegoz, Mathias','POL Editeur',19);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Hétel du Grand Cerf','Bartelt, Franz','Le Seuil',19);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Des garéons bien élevés','Parsons, Tony','DLM',18);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('émilie voit quelqu''un - Aprés la psy, le beau temps ?','Rouquette, Anne','Fluide Glacial',18);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Le Labyrinthe des esprits','Zafon, Carlos ruiz','Actes Sud Littérature',18);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('L''anniversaire du roi','Trillard, Marc','éEditions Actes Sud',17);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('L''écrivain national','Joncour, Serge','Flammarion',17);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Chétiments','McDermid, Val','Flammarion',17);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Rouen 1203','Aillon, Jean d''','Flammarion',17);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Un maniaque dans la ville','Kellerman, Jonathan','Seuil',17);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Blind Lake','Wilson, Robert Charles','Editions Gallimard',17);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('La Maison des Turner','Flournoy, Angela','Les escales Editions',17);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Sécurité','Wohlsdorf, Gina','Actes Sud Littérature',17);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('é son image','Ferrari, Jéréme','Actes Sud Littérature',17);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('La délicatesse','Bonin, Cyril','Futuropolis',17);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Les fantémes du vieux pays','Hill, Nathan','Editions Gallimard',17);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Le Temps des regrets','Higgins Clark, Mary','Albin Michel',16);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Dans le jardin de l''ogre','Slimani, Leéla','Editions Gallimard',16);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('L''amour et les foréts','Reinhardt E éric','Editions Gallimard',16);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Un secret du docteur Freud','Abécassis, Eliette','Flammarion',16);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('La route sombre','Ma, Jian','Flammarion',16);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Sous l''eau','Levy, Deborah','Flammarion',16);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Soleil de nuit','Nesbo, Jo','Editions Gallimard',16);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Un coeur sombre','Ellory, R. J.','Sonatine',16);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Danser dans la poussiére','Cook, Thomas H.','Le Seuil',16);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Feu follet','Melo, Patricia','éEditions Actes Sud',16);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Une Jeunesse','Modiano, Patrick','Editions Gallimard',15);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('éa aussi, éa passera','Busquets, Milena','Editions Gallimard',15);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Laétitia ou la fin des hommes','Jablonka, Ivan','Seuil',15);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Les infémes','Miller, Jax','Ombres Noires',15);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('L''éle Louvre','Chavouet, Florent','Futuropolis',15);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Eugenia','Duroy, Lionel','Julliard',15);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Un moindre mal','Flanagan, Joe','éEditions Gallmeister',15);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Idaho','Ruskovich, Emily','Editions Gallmeister',15);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Boussole','Enard, Mathias','éEditions Actes Sud',14);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Le prix Nobel','Alexieva, Elena','éEditions Actes Sud',14);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('La poupée de Kafka','Colin, Fabrice','éEditions Actes Sud',14);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Mr Gwyn','Baricco, Alessandro','Editions Gallimard',14);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Les mécanos de Vénus','Lansdale, Joe R.','Editions Denoél',14);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Tombée du ciel','Ahern, Cecelia','Flammarion',14);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Trois fois dés l''aube','Baricco, Alessandro','Editions Gallimard',14);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('La Vengeance des méres','Ferus, Jim','Le Cherche Midi',14);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Indu Boy','Clément, Catherine','Le Seuil',14);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Le commis','Malamud, Bernard','Rivages',14);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Les Chants de la mort','Gonthier, Nicole','Pygmalion',13);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Landfall','Urbani, Ellen','éEditions Gallmeister',13);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('La Jeune épouse','Baricco, Alessandro','Editions Gallimard',13);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Les Furies','Groff, Lauren','L''Olivier',13);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Un déluge de feu','Ghosh, Amitav','Robert Laffont',13);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Une illusion d''optique','Penny, Louise','éEditions Actes Sud',13);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Sidney Chambers et les périls de la nuit','Runcie, James','éEditions Actes Sud',13);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Farallon Islands','Geni, Abby','éEditions Actes Sud',13);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Mélodie de Vienne','Lothar, Ernst','Liana Levi',13);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Les filles au lion','Burton, Jessie','Editions Gallimard',13);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Cabaret Biarritz','Vales, José C.','Editions Denoél',13);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('La salle de bal','Hope, Anna','Editions Gallimard',13);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('L''affaire Collini','Schirach, Ferdinand von','Editions Gallimard',12);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Tarpeia, les venins de Rome','Bouchard, Nicolas','Flammarion',12);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Les Vies multiples d''Amory Clay','Boyd, William','Seuil',12);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('A mains nues','Barbato, Paola','Editions Denoél',12);
INSERT INTO livre(Titre,Auteur,Editeur,Total_des_préts) VALUES ('Il était une ville','Reverdy, Thomas B.','Flammarion',12);
